apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: task-tracker-test
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: local-k3s
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: kafka-service:9092
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/kafka"
        ports:
        - containerPort: 8080
          name: http