apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-tracker-prod # Это укажет Argo CD разворачивать этот сервис в прод-неймспейс
resources:
  - ../../../base/monitoring    # Ссылка на ту же базу