apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-tracker-prod
resources:
- ../../../base/monitoring
- ingress.yaml
patches:
- target:
    kind: ConfigMap
    name: prometheus-grafana
  patch: |-
    - op: replace
      path: /data/grafana.ini
      value: |
        [server]
        http_port = 3000
        root_url = %(protocol)s://%(domain)s:%(http_port)s/prod/grafana/
        serve_from_sub_path = true