apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: almaz8412/task-tracker:latest  # Тот самый образ, который теперь в Docker Hub
        ports:
        - containerPort: 8000
        env:
        - name: DB_PASSWORD
          value: "password"
        envFrom:
        - configMapRef:
            name: app-config