apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: almaz8412/task-tracker:latest # Например: almaz/task-tracker:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_PASSWORD
          value: "password" # В идеале использовать Secret, но пока для теста здесь
        envFrom:
        - configMapRef:
            name: app-config