apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-tracker-prod # Все ресурсы приедут сюда
resources:
  - ../../base/backend
  - ../../base/consumer
  - ../../base/database
  - ../../base/kafka
  - ../../base/monitoring