apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-tracker-prod

resources:
- ../../../base/frontend
- ingress.yaml

images:
- name: almaz8412/task-tracker-frontend
  newTag: prod-3518ecd