apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-deployment.yaml
  - grafana-svc.yaml
  - service-account.yaml
  - grafana-config.yaml
  - grafana-secret.yaml
  - opensearch-statefulset.yaml
  - opensearch-dashboards.yaml
  - fluent-bit-config.yaml
  - fluent-bit-daemonset.yaml
  - grafana-datasource.yaml
  - grafana-dashboard-provider.yaml
  - grafana-dashboard-task-tracker.yaml
