apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
      annotations:
        fluentbit.io/parser: json
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: consumer
        image: almaz8412/consumer:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "task-created"
        - name: KAFKA_GROUP_ID
          value: "consumer-group"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD