apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: task-tracker-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: backend
        env: test
        revision: develop
      - name: backend
        env: prod
        revision: main
      - name: frontend
        env: test
        revision: develop
      - name: frontend
        env: prod
        revision: main
      - name: kafka
        env: test
        revision: develop
      - name: kafka
        env: prod
        revision: main
      - name: database
        env: test
        revision: develop
      - name: database
        env: prod
        revision: main
      - name: consumer
        env: test
        revision: develop
      - name: consumer
        env: prod
        revision: main
      - name: monitoring
        env: test
        revision: develop
      - name: monitoring
        env: prod
        revision: main
  template:
    metadata:
      name: '{{env}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Almaz-R/task-tracker.git
        targetRevision: '{{revision}}'
        path: kustomize/overlays/{{env}}/{{name}}
      destination:
        server: https://kubernetes.default.svc
        namespace: 'task-tracker-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
            - /status
            - /spec/template/metadata/labels
            - /metadata/resourceVersion
            - /metadata/uid
            - /metadata/generation
            - /metadata/annotations
            - /spec/template/spec/containers/0/terminationMessagePath
            - /spec/template/spec/containers/0/terminationMessagePolicy
            - /spec/template/spec/containers/0/imagePullPolicy
            - /spec/template/spec/dnsPolicy
            - /spec/template/spec/restartPolicy
            - /spec/template/spec/schedulerName
            - /spec/template/spec/securityContext
            - /spec/template/spec/terminationGracePeriodSeconds
        - group: ""
          kind: Service
          jsonPointers:
            - /status
            - /metadata/resourceVersion
            - /metadata/uid
            - /metadata/generation
            - /metadata/annotations
            - /spec/clusterIP
            - /spec/clusterIPs
            - /spec/internalTrafficPolicy
            - /spec/externalTrafficPolicy
            - /spec/ports
            - /metadata/labels