apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-services
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: backend
        path: services/backend
      - name: kafka
        path: services/kafka
      - name: database
        path: services/database
      - name: consumer
        path: services/consumer
      - name: monitoring
        path: services/monitoring
  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/Almaz-R/task-tracker.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
      # ЭТОТ БЛОК ИСПРАВИТ ОРАНЖЕВЫЙ СТАТУС:
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
            - /status
            - /spec/template/metadata/labels
            - /metadata/resourceVersion
            - /metadata/uid
            - /metadata/generation
            - /metadata/annotations/deployment.kubernetes.io~1revision
            - /spec/template/spec/containers/0/terminationMessagePath
            - /spec/template/spec/containers/0/terminationMessagePolicy
            - /spec/template/spec/containers/0/imagePullPolicy
            - /spec/template/spec/dnsPolicy
            - /spec/template/spec/restartPolicy
            - /spec/template/spec/schedulerName
            - /spec/template/spec/securityContext
            - /spec/template/spec/terminationGracePeriodSeconds
        - group: ""
          kind: Service
          jsonPointers:
            - /status
            - /metadata/resourceVersion
            - /metadata/uid
            - /metadata/generation