apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-tracker-prod
resources:
- ../../../base/kafka
- ingress.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kafka-ui
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: "/prod/kafka"